### ISSUE TITLE
LL: OPAMP functional modes assert incomplete

### ISSUE THREAD

**Issue by diggit** [STMicroelectronics/stm32f3xx_hal_driver#1]
**Describe the set-up**
 * custom board, not directly relevant to issue
 * GCC 10.2, cmake, ninja

**Describe the bug**
[These two functional modes](https://github.com/STMicroelectronics/stm32f3xx_hal_driver/blob/master/Inc/stm32f3xx_ll_opamp.h#L141) are not allowed by [checking macro](https://github.com/STMicroelectronics/stm32f3xx_hal_driver/blob/master/Src/stm32f3xx_ll_opamp.c#L52) and causes [assertion](https://github.com/STMicroelectronics/stm32f3xx_hal_driver/blob/master/Src/stm32f3xx_ll_opamp.c#L148) when used.

Funtional modes: 
```c
#define LL_OPAMP_MODE_STANDALONE        (0x00000000U)                               /*!< OPAMP functional mode, OPAMP operation in standalone */
#define LL_OPAMP_MODE_FOLLOWER          (OPAMP_CSR_VMSEL_1 | OPAMP_CSR_VMSEL_0)     /*!< OPAMP functional mode, OPAMP operation in follower */
#define LL_OPAMP_MODE_PGA               (OPAMP_CSR_VMSEL_1)                         /*!< OPAMP functional mode, OPAMP operation in PGA */
#define LL_OPAMP_MODE_PGA_EXT_FILT_IO0  (OPAMP_CSR_PGGAIN_3                      | OPAMP_CSR_VMSEL_1) /*!< OPAMP functional mode, OPAMP operation in PGA with external filtering on OPAMP input IO0. */
#define LL_OPAMP_MODE_PGA_EXT_FILT_IO1  (OPAMP_CSR_PGGAIN_3 | OPAMP_CSR_PGGAIN_2 | OPAMP_CSR_VMSEL_1) /*!< OPAMP functional mode, OPAMP operation in PGA with external filtering on OPAMP input IO1. */
```

Macro used in assert.
```c
#define IS_LL_OPAMP_FUNCTIONAL_MODE(__FUNCTIONAL_MODE__)                       \
  (   ((__FUNCTIONAL_MODE__) == LL_OPAMP_MODE_STANDALONE)                      \
   || ((__FUNCTIONAL_MODE__) == LL_OPAMP_MODE_FOLLOWER)                        \
   || ((__FUNCTIONAL_MODE__) == LL_OPAMP_MODE_PGA)                             \
  )
```

Clearly, macro does not accept `LL_OPAMP_MODE_PGA_EXT_FILT_IO0` and `LL_OPAMP_MODE_PGA_EXT_FILT_IO1` functional modes.

**How To Reproduce**
1.  have code like
```c
	LL_OPAMP_InitTypeDef OPAMP_InitStruct {};
	
	OPAMP_InitStruct.FunctionalMode = LL_OPAMP_MODE_PGA_EXT_FILT_IO1;
	OPAMP_InitStruct.InputNonInverting = LL_OPAMP_INPUT_NONINVERT_IO0;
	OPAMP_InitStruct.InputInverting = LL_OPAMP_INPUT_INVERT_IO1;
	LL_OPAMP_Init(OPAMP2, &OPAMP_InitStruct);
```

2. enable assertions by defining `USE_FULL_ASSERT`
3. compile and run
4. assertion occurs on valid functional mode

**Comment by ASELSTM** [comment]
Hi @diggit,

Thank you for this report. The issue has been forwarded to our development teams. We will get back to you as soon as they provide us with their feedback.

With regards,

**Comment by ASELSTM** [comment]
Hi @diggit,

Referring to our development team, to be able to use the PGA external filtering,  OPAMP should be configured in 2 steps:

1. Use LL_OPAMP_Init() with the FunctionalMode param configured as **"LL_OPAMP_MODE_PGA"**.

2. Use the LL_OPAMP_SetFunctionalMode() to configure the PGA external filtering with the desired config **LL_OPAMP_MODE_PGA_EXT_FILT_IO**0 or **LL_OPAMP_MODE_PGA_EXT_FILT_IO1**. 

Thus, the actual implementation of the IS_LL_OPAMP_FUNCTIONAL_MODE is correct, the macro should not accept `LL_OPAMP_MODE_PGA_EXT_FILT_IO0` and `LL_OPAMP_MODE_PGA_EXT_FILT_IO1` . However, we agree to say that the driver is not clear enough regarding this. Our development teams will work on it and will propose some enhancement. 

Thank you once again for your contribution and thank you for drawing our attention to this.

With regards,
